# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4e346c208d0c6718723d60bb0b6a99510c50fc7e610e051aca04d0b90a2b78826d54ad912e237cf14697f365a332fab012d628ac8c05845e16303fe1a21434a

test:
  secret_key_base: 65d180f521fc796e4ef0780162b05feee5becb6e3b6d5727a52c3129f5c12cb40628783e39b15fe18fbfe95e6a24906fbd15bce5df9050f245d1b3a40d464823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
